---
apiVersion: v1
kind: Service
metadata:
  name: media-frontend
  labels:
    death-star-project: social-network
    app: media-frontend
  namespace: ai4cloudops-f7f10d9
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    death-star-project: social-network
    app: media-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-frontend
  labels:
    death-star-project: social-network
    app: media-frontend
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-frontend
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: media-frontend
      name: media-frontend
    spec:
      containers:
      - name: media-frontend
        image: registry-route-ai4cloudops-11855c.apps.shift.nerc.mghpcc.org/media-frontend:xenial
        resources:
          requests:
            cpu: 1
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 5000Mi

        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/local/openresty/nginx/client_body_temp
          name: site-data
        - mountPath: /usr/local/openresty/nginx/proxy_temp
          name: site-data
        - mountPath: /usr/local/openresty/nginx/fastcgi_temp
          name: site-data
        - mountPath: /usr/local/openresty/nginx/uwsgi_temp
          name: site-data
        - mountPath: /usr/local/openresty/nginx/scgi_temp
          name: site-data
        - mountPath: /usr/local/openresty/nginx/logs
          name: site-data
        - mountPath: /usr/local/openresty/nginx/lua-scripts
          name: lua-conf
        - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
          subPath: nginx.conf
          name: nginx-conf
        - mountPath: /usr/local/openresty/nginx/conf/jaeger-config.yml
          subPath: jaeger-config.yml
          name: jaeger-conf

      imagePullSecrets:
        - name: customregred
      restartPolicy: Always
      volumes:
      - name: nginx-conf
        configMap:
          name: media-frontend-nginx
          items:
          - key: nginx.conf
            path: nginx.conf
      - name: lua-conf
        configMap:
          name: media-frontend-lua
      - name: jaeger-conf
        configMap:
          name: jaeger-config-yaml
      - name: site-data
        emptyDir: {}