---
apiVersion: v1
kind: Service
metadata:
  name: media-memcached
  labels:
    death-star-project: social-network
    app: media-memcached
  namespace: ai4cloudops-f7f10d9
spec:
  ports:
  - port: 11211
  selector:
    death-star-project: social-network
    app: media-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-memcached
  labels:
    death-star-project: social-network
    app: media-memcached
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: media-memcached
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: media-memcached
      name: media-memcached
    spec:
      containers:
      - name: media-memcached
        image: memcached
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 500Mi

      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
