---
apiVersion: v1
kind: Service
metadata:
  name: post-storage-mongodb
  labels:
    death-star-project: social-network
    app: post-storage-mongodb
  namespace: ai4cloudops-f7f10d9
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: post-storage-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-storage-mongodb
  labels:
    death-star-project: social-network
    app: post-storage-mongodb
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: post-storage-mongodb
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: post-storage-mongodb
      name: post-storage-mongodb
    spec:
      containers:
      - name: post-storage-mongodb
        image: registry-route-ai4cloudops-11855c.apps.shift.nerc.mghpcc.org/mongo
        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
        resources:
          requests:
            cpu: 1
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 5000Mi


      restartPolicy: Always

      volumes:
      - name: my-data
        emptyDir: {}
      imagePullSecrets:
        - name: customregred
