---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-redis
  labels:
    death-star-project: social-network
    app: social-graph-redis
  namespace: ai4cloudops-f7f10d9
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: social-network
    app: social-graph-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-redis
  labels:
    death-star-project: social-network
    app: social-graph-redis
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: social-graph-redis
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: social-graph-redis
      name: social-graph-redis
    spec:
      containers:
      - name: social-graph-redis
        image: registry-route-ai4cloudops-11855c.apps.shift.nerc.mghpcc.org/redis
        resources:
          requests:
            cpu: 1
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 5000Mi

        volumeMounts:
          - name: ephemeral-storage
            mountPath: /data

      restartPolicy: Always
      imagePullSecrets:
        - name: customregred
      volumes:
        - name: ephemeral-storage
          emptyDir: { }
