---
apiVersion: v1
kind: Service
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: social-network
    app: social-graph-mongodb
  namespace: ai4cloudops-f7f10d9
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: social-graph-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-graph-mongodb
  labels:
    death-star-project: social-network
    app: social-graph-mongodb
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: social-graph-mongodb
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: social-graph-mongodb
      name: social-graph-mongodb
    spec:
      containers:
      - name: social-graph-mongodb
        image: registry-route-ai4cloudops-11855c.apps.shift.nerc.mghpcc.org/mongo
        resources:
          requests:
            cpu: 1
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 5000Mi

        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
      restartPolicy: Always
      volumes:
      - name: my-data
        emptyDir: {}
      imagePullSecrets:
        - name: customregred
