---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-client
  labels:
    death-star-project: social-network
    app: ubuntu-client
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: ubuntu-client
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: ubuntu-client
      name: ubuntu-client
    spec:
      containers:
      - name: ubuntu-client
        image: smqasim/ubuntu-client:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 500Mi

        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: Always
#          - apt-get -y update &&
#            apt-get -y upgrade &&
#            apt-get -y install dnsutils git vim python3 python3-aiohttp libssl-dev libz-dev luarocks iputils-ping lynx build-essential gcc bash curl &&
#            luarocks install luasocket &&
#            sleep 365d
      restartPolicy: Always

