---
apiVersion: v1
kind: Service
metadata:
  name: user-mongodb
  labels:
    death-star-project: social-network
    app: user-mongodb
  namespace: ai4cloudops-f7f10d9
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: social-network
    app: user-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongodb
  labels:
    death-star-project: social-network
    app: user-mongodb
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: user-mongodb
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: user-mongodb
      name: user-mongodb
    spec:
      containers:
      - name: user-mongodb
        image: mongo
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 500Mi

        volumeMounts:
          - name: my-data
            mountPath: "/data/db"
      restartPolicy: Always
      volumes:
      - name: my-data
        emptyDir: {}
      imagePullSecrets:
        - name: regcred
