---
apiVersion: v1
kind: Service
metadata:
  name: user-timeline-service
  labels:
    death-star-project: social-network
    app: user-timeline-service
  namespace: ai4cloudops-f7f10d9
spec:
  ports:
  - port: 9090
  selector:
    death-star-project: social-network
    app: user-timeline-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-timeline-service
  labels:
    death-star-project: social-network
    app: user-timeline-service
  namespace: ai4cloudops-f7f10d9
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: social-network
      app: user-timeline-service
  template:
    metadata:
      labels:
        death-star-project: social-network
        app: user-timeline-service
      name: user-timeline-service
    spec:
      containers:
      - name: user-timeline-service
        image: smqasim/social-network-microservices:latest
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 2000m
            memory: 500Mi

        command: ["UserTimelineService"]
        volumeMounts:
          - mountPath: /social-network-microservices/config/jaeger-config.yml
            subPath: jaeger-config.yml
            name: jaeger-conf-yaml
          - mountPath: /social-network-microservices/config/service-config.json
            subPath: service-config.json
            name: service-config-json
      restartPolicy: Always
      volumes:
        - name: jaeger-conf-yaml
          configMap:
            name: jaeger-config-yaml
        - name: service-config-json
          configMap:
            name: service-config-json
      imagePullSecrets:
        - name: regcred
